version: '3.9'
services:
    api:
        build: .
        container_name: nest-api
        expose:
            - '3000' # visível só para o host/nginx
        env_file:
            - .env
        restart: unless-stopped
