services:
    nest-api:
        build:
            context: .
            dockerfile: Dockerfile
        image: gru.ocir.io/grs29rbpghiq/cidadeclipse/backend-cd:latest
        ports:
            - '3000:3000'
        env_file:
            - .env
        restart: always
