name: Deploy to Oracle VM

on:
    push:
        tags:
            - 'deploy-*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint

            - name: Login no OCIR
              run: echo "${{ secrets.OCIR_TOKEN }}" | docker login gru.ocir.io -u "${{ secrets.OCIR_USERNAME }}" --password-stdin

            - name: Build da imagem
              run: docker-compose -f docker-compose.prod.yml build

            - name: Push da imagem
              run: docker-compose -f docker-compose.prod.yml push

            - name: Deploy remoto via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VM_HOST }}
                  username: ${{ secrets.VM_USER }}
                  key: ${{ secrets.VM_SSH_KEY }}
                  script: |
                      docker login gru.ocir.io -u "${{ secrets.OCIR_USERNAME }}" --password "${{ secrets.OCIR_TOKEN }}"
                      cd /home/ubuntu/projeto/backend-cd
                      docker-compose -f docker-compose.prod.yml pull
                      docker-compose -f docker-compose.prod.yml up -d
